spring:
  profiles: default
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    #url: jdbc:postgresql://service-registry:5432/postgres
    username: postgres
    password: Dell123$

logging:
  level:
    root: INFO
    com.af5m.elm: TRACE
  file: /var/log/af5m/elm-service-persistence.log

---

spring:
  profiles: linked
  datasource:
    platform: postgres
    url: jdbc:postgresql://##SERVER##:##PORT##/postgres
    username: postgres
    password: ##PASSWORD##